// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYj0I_cE8FSrWp_I-XDo6pkfB5Y-1b-rc',
    appId: '1:830394026266:android:ca180dddbd69721ce004a3',
    messagingSenderId: '830394026266',
    projectId: 'studentmanagementapp-4c49b',
    databaseURL:
        'https://studentmanagementapp-4c49b-default-rtdb.firebaseio.com',
    storageBucket: 'studentmanagementapp-4c49b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYj0I_cE8FSrWp_I-XDo6pkfB5Y-1b-rc',
    appId: '1:830394026266:ios:ca180dddbd69721ce004a3',
    messagingSenderId: '830394026266',
    projectId: 'studentmanagementapp-4c49b',
    databaseURL:
        'https://studentmanagementapp-4c49b-default-rtdb.firebaseio.com',
    storageBucket: 'studentmanagementapp-4c49b.firebasestorage.app',
    iosBundleId: 'com.example.studentmanagementapp',
  );
}
